### ISSUE TITLE
WebPage simplyfy

### ISSUE THREAD

**Issue by qawsed55** [tobi01001/LED_Stripe_Dynamic_web_conf#16]
Hello! Sorry for pore English.
I think webpage is very hard to manipulate.
May be it would be great if put some settings to additional webpage? For example - there may be such settings as: Color blend type, Color temperature, Reverse, Current limit, Reset default values, FPS and may be some others.
For now - webpage is very hard, as for me.

And one more "to do": it would be great if we are able to save settings for effects. For example, if we set SPEED as 120 - it great looks with RAINBOW effect. But not good with some other.
May be make "speed_coefficient" var for each effects and we would ne able to change SPEED more "looks good" for each effect.

Also, playlist with different setting - great additional functionality, but it need too much code, as I know. But, may be someone can help witn this (I'm not programmer).

Dynamic pallete with three or four  colorPIckers - great funct too.
Thanks. You make great project.

**Comment by tobi01001** [comment]
Hi,
Thanks for the feedback.

**Web Page:**
In fact the web page has grown a lot...
I am currently working in a branch called "Knob Control" https://github.com/tobi01001/LED_Stripe_Dynamic_web_conf/tree/KnobControl which enables controlling the complete LEDs with a rotary encoder (with button) and a small OLED display.

In this I already rearranged the web page settings a bit. Also, klicking on a header in the web page will close the relevant section. Maybe its woth hiding some is these by default but you can start with that. 
I need to look into that to see how to maybe further improve....

**Speed**
In general, the speed parameter is relative to time (i.e. millis()). However, it also depends on the number of LEDs and some effects on "processing time". That makes it hard. I tried to optimize already but if for instance we have a speed wich translates to beats per minute and the effects moves a bar from left to right with "Speed" moves per minute it will look quite slow on short strips and quite fast on long setups...

To save / set the speed on a "per effect" base could be a good idea which I need to look at (it's a question of memory consumption as well...).
Speed coefficient does unfortunately not work for different LED Counts....

**PlayList**
Yeah, it seems to be quite an effort to implement this. On then other side, it is easily possible right now if you do this externally with HTML requests. In my case I have a wakeup-sequence controlled by FHEM - (home automation SW) where I set different effects with different color palettes, speed etc... It can be combined into one "HTML call" and with this you can control a playlist from external...

**Dynamic Palette:**
I'll put this on the list but this would even more blow up the web page.

**P.S.:**
I put a lot of work into this but the majority is based on the great libraries being initially used and just modified (perverted) for my personal use....

**Comment by qawsed55** [comment]
>Speed coefficient does unfortunately not work for different LED Counts....
Is hard to tell in English.... For example: Effect1 looks good with SpeedSetting from 15 to 50. Effect2 - 150:200. 
Coefficient can help us in this case, as I think. It is not great solution, but it simple and easy to realise ( I do not insist )) )
**PlayList**
> if you do this externally with HTML requests
In this case we can realise this functionality with Java. May be someone can write code? :) Settings we can put in text file to ESP filesystem and Java need to read, parce and send to ESP.
**Dynamic Palette:** if we make it on another page - it will be normal. [Here](http://jscolor.com/examples/) good examples. (It is just as idea, may be it can be usefull) 

>I put a lot of work into this but the majority is based on the great libraries 
Yes, I'm understand. Do not think, that I ask you TO DO! I'm just say what I think and if something of this you will find usefull and you realise it - It would be great. Sorry! I'm uderstand, that it is just your needs, shared for everybody.

**Comment by tobi01001** [comment]
Closing this one as suggestions are tracked here:
#22 
#23 
#24 
#25
